---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-http-sd-endpoint-config
  labels:
    app: prom-http-sd-endpoint
data:
  targets.yaml: |
    jobs:
      - name: exporter1
        targets:
          - 1.1.1.1:9001
          - 2.2.2.2:9001
        labels:
          env: prod
          dc: dc1
      - name: exporter2
        targets:
          - 3.3.3.3:9002
          - 4.4.4.4:9002
        labels:
          env: prod
          dc: dc2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-http-sd-endpoint
  labels:
    app: prom-http-sd-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-http-sd-endpoint
  template:
    metadata:
      labels:
        app: prom-http-sd-endpoint
    spec:
      containers:
      - name: prom-http-sd-endpoint
        image: rajmor/prom-http-sd-endpoint:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: prom-http-sd-endpoint-config
---
apiVersion: v1
kind: Service
metadata:
  name: prom-http-sd-endpoint
  labels:
    app: prom-http-sd-endpoint
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: prom-http-sd-endpoint
